Improve formatting and cleanup margins

diff --git a/dev/start b/dev/start
--- a/dev/start
+++ b/dev/start
@@ -10,12 +10,13 @@ source "../ci/oauth/keycloak/keycloak_functions.sh"
 
 print_help() {
   cat << EOF
-Starts Conjur for development. Once setup is complete, the user is dropped into the Conjur container.
-To start the application server, run:
+Starts Conjur for development. Once setup is complete, the user is dropped into
+the Conjur container.  To start the application server, run:
     # conjurctl server
 
 Usage: start [options]
-    --authn-ldap    Starts OpenLDAP server and loads a demo policy to enable authentication via:
+    --authn-ldap    Starts OpenLDAP server and loads a demo policy to enable 
+                    authentication via:
                     'curl -X POST -d "alice" http://localhost:3000/authn-ldap/test/cucumber/alice/authenticate'
     --rotators      Starts a cucumber and test postgres container.
                     Drops you into the cucumber container.
@@ -84,29 +85,48 @@ function conjur_isready?() {
         sleep $sleep
    fi
   done
-  echo "Error with conjur server start or it is too slow"
+
+  echo "Conjur server failed to come up in time."
   return 1
 }
 
 configure_oidc_authenticators() {
   # add variables' values for keycloak
   echo "Setting keycloak variables values in conjur"
-  docker-compose exec client conjur policy load root /src/conjur-server/ci/test_suites/authenticators_oidc/policy.yml
-  docker-compose exec client conjur variable values add conjur/authn-oidc/keycloak/provider-uri "https://keycloak:8443/auth/realms/master"
-  docker-compose exec client conjur variable values add conjur/authn-oidc/keycloak/id-token-user-property "preferred_username"
+  docker-compose exec client \
+    conjur policy load root \
+    /src/conjur-server/ci/test_suites/authenticators_oidc/policy.yml
+  docker-compose exec client \
+    conjur variable values add \
+    conjur/authn-oidc/keycloak/provider-uri \
+    "https://keycloak:8443/auth/realms/master"
+  docker-compose exec client \
+    conjur variable values add \
+    conjur/authn-oidc/keycloak/id-token-user-property "preferred_username"
 
   if [[ $ENABLE_OIDC_OKTA = true ]]; then
       # add variables' values for okta
-      docker-compose exec client conjur policy load root /src/conjur-server/ci/authn-oidc/policy_okta.yml
-      docker-compose exec client conjur variable values add conjur/authn-oidc/okta/provider-uri "https://dev-842018.oktapreview.com"
-      docker-compose exec client conjur variable values add conjur/authn-oidc/okta/id-token-user-property "preferred_username"
+      docker-compose exec client \
+        conjur policy load root /src/conjur-server/ci/authn-oidc/policy_okta.yml
+      docker-compose exec client \
+        conjur variable values add conjur/authn-oidc/okta/provider-uri \
+        "https://dev-842018.oktapreview.com"
+      docker-compose exec client \
+        conjur variable values add \
+        conjur/authn-oidc/okta/id-token-user-property "preferred_username"
   fi
 
   if [[ $ENABLE_OIDC_ADFS = true ]]; then
     # add variables' values for ADFS
-    docker-compose exec client conjur policy load root /src/conjur-server/ci/authn-oidc/policy_adfs.yml
-    docker-compose exec client conjur variable values add conjur/authn-oidc/adfs/provider-uri https://adfs4win2016.northeurope.cloudapp.azure.com
-    docker-compose exec client conjur variable values add conjur/authn-oidc/adfs/id-token-user-property "unique_name"
+    docker-compose exec client \
+      conjur policy load root /src/conjur-server/ci/authn-oidc/policy_adfs.yml
+    docker-compose exec client \
+      conjur variable values add \
+      conjur/authn-oidc/adfs/provider-uri \
+      https://adfs4win2016.northeurope.cloudapp.azure.com
+    docker-compose exec client \
+      conjur variable values add \
+      conjur/authn-oidc/adfs/id-token-user-property "unique_name"
   fi
 }
 
@@ -115,13 +135,15 @@ fetch_oidc_certificates() {
 
   if [[ $ENABLE_OIDC_ADFS = true ]]; then
     echo "Initialize ADFS certificate in conjur server"
-    docker-compose exec conjur /src/conjur-server/dev/files/authn-oidc/adfs/fetchCertificate
+    docker-compose exec conjur \
+      /src/conjur-server/dev/files/authn-oidc/adfs/fetchCertificate
   fi
 }
 
 enable_oidc_authenticators() {
   echo "Configuring Keycloak as OpenID provider for automatic testing"
-  # We enable an OIDC authenticator without a service-id to test that it's invalid
+  # We enable an OIDC authenticator without a service-id to test that it's
+  # invalid.
   enabled_authenticators="$enabled_authenticators,authn-oidc/keycloak,authn-oidc"
 
   if [[ $ENABLE_OIDC_OKTA = true ]]; then
@@ -216,7 +238,9 @@ if [[ $ENABLE_AUTHN_LDAP = true ]]; then
 
   enabled_authenticators="$enabled_authenticators,authn-ldap/test,authn-ldap/secure"
 
-  docker-compose exec conjur conjurctl policy load cucumber /src/conjur-server/dev/files/authn-ldap/policy.yml
+  docker-compose exec conjur \
+    conjurctl policy load cucumber \
+    "/src/conjur-server/dev/files/authn-ldap/policy.yml"
 fi
 
 if [[ $ENABLE_AUTHN_AZURE = true ]]; then
@@ -224,14 +248,25 @@ if [[ $ENABLE_AUTHN_AZURE = true ]]; then
 
   ../ci/authn-azure/check_dependencies.sh
 
-  docker-compose exec client conjur policy load root /src/conjur-server/ci/test_suites/authenticators_azure/policies/policy.yml
-  docker-compose exec client conjur variable values add conjur/authn-azure/prod/provider-uri "https://sts.windows.net/$AZURE_TENANT_ID/"
+  docker-compose exec client \
+    conjur policy load root \
+    "/src/conjur-server/ci/test_suites/authenticators_azure/policies/policy.yml"
+  docker-compose exec client \
+    conjur variable values add \
+    conjur/authn-azure/prod/provider-uri "https://sts.windows.net/$AZURE_TENANT_ID/"
 
-  sed "s#{{ AZURE_SUBSCRIPTION_ID }}#$AZURE_SUBSCRIPTION_ID#g" ../ci/authn-azure/policies/azure-hosts.template.yml |
-    sed "s#{{ AZURE_RESOURCE_GROUP }}#$AZURE_RESOURCE_GROUP#g" > ../ci/authn-azure/policies/azure-hosts.yml
-  docker-compose exec client conjur policy load root /src/conjur-server/ci/authn-azure/policies/azure-hosts.yml
+  sed "s#{{ AZURE_SUBSCRIPTION_ID }}#$AZURE_SUBSCRIPTION_ID#g" \
+    "../ci/authn-azure/policies/azure-hosts.template.yml" |
+    sed "s#{{ AZURE_RESOURCE_GROUP }}#$AZURE_RESOURCE_GROUP#g" > \
+    "../ci/authn-azure/policies/azure-hosts.yml"
 
-  docker-compose exec client conjur policy load root /src/conjur-server/ci/authn-azure/policies/azure-operators.yml
+  docker-compose exec client \
+    conjur policy load root \
+    "/src/conjur-server/ci/authn-azure/policies/azure-hosts.yml"
+
+  docker-compose exec client \
+    conjur policy load root \
+    "/src/conjur-server/ci/authn-azure/policies/azure-operators.yml"
 fi
 
 if [[ $ENABLE_AUTHN_GCP = true ]]; then
@@ -243,16 +278,19 @@ if [[ $ENABLE_AUTHN_JWT = true ]]; then
   services+=(jwks jwks_py keycloak)
   docker-compose up -d --no-deps "${services[@]}"
 
-  # OIDC is a special case on JWT, JWT automation tests contain scenarios with OIDC providers
+  # OIDC is a special case on JWT, JWT automation tests contain scenarios with
+  # OIDC providers.
   configure_oidc_providers
 
   echo "Configure jwks provider"
   docker-compose exec jwks "/tmp/create_nginx_certificate.sh"
 fi
 
-if [[ $ENABLE_AUTHN_OIDC = false && ($ENABLE_OIDC_ADFS = true || $ENABLE_OIDC_OKTA = true) ]]; then
-    echo "Error: --oidc-adfs/--oidc-okta should be configured as part of --authn-oidc"
-    exit 1
+if [[ $ENABLE_AUTHN_OIDC = false && 
+  ($ENABLE_OIDC_ADFS = true || $ENABLE_OIDC_OKTA = true) ]]
+then
+  echo "Error: --oidc-adfs/--oidc-okta should be configured as part of --authn-oidc"
+  exit 1
 fi
 
 if [[ $ENABLE_AUTHN_OIDC = true ]]; then
@@ -267,7 +305,8 @@ if [[ $ENABLE_AUTHN_OIDC = true ]]; then
     docker-compose up -d --no-deps "${services[@]}"
 
     echo "Starting Okta agent service"
-    Docker exec "$(docker-compose ps -q okta-ldap-agent)" /opt/Okta/OktaLDAPAgent/scripts/OktaLDAPAgent
+    docker exec "$(docker-compose ps -q okta-ldap-agent)" \
+      "/opt/Okta/OktaLDAPAgent/scripts/OktaLDAPAgent"
   fi
 fi
 
@@ -278,7 +317,9 @@ fi
 if [[ $ENABLE_AUTHN_IAM = true ]]; then
   enabled_authenticators="$enabled_authenticators,authn-iam/prod"
 
-  docker-compose exec conjur conjurctl policy load cucumber /src/conjur-server/dev/files/authn-iam/policy.yml
+  docker-compose exec conjur \
+    conjurctl policy load cucumber \
+    "/src/conjur-server/dev/files/authn-iam/policy.yml"
 fi
 
 echo "Setting CONJUR_AUTHENTICATORS to: $enabled_authenticators"
@@ -294,7 +335,8 @@ if [[ "$enabled_authenticators" != "$default_authenticators" ]]; then
 fi
 
 echo "Creating user alice"
-docker-compose exec client conjur policy load root /src/conjur-server/dev/files/policy.yml
+docker-compose exec client \
+  conjur policy load root "/src/conjur-server/dev/files/policy.yml"
 
 echo "killing the conjur server process"
 docker-compose exec conjur /src/conjur-server/dev/files/killConjurServer
