Collect coverage Reports pre merge
The conjur pipeline generates coverage reports in all of its branches,
most of which are merged together into a single report by simplecov
itself. This isn't possible for the gke report, so that is merged in
with jq. Recenly this has failed, this commit is for capturing more
information in order to determine why it's failing.

This is related to 15ee5b9ed4fc912bfd68c1565ef466b4bf80c24b which
moved artifact archival before merge, however that means only
the pre merge reports can be archived.

This commit ensures the source and merged reports are captured.
It also adds some explicit tests to the script so that if a report
is empty it will be noted in the console log.

Related: conjurinc/ops#516

diff --git a/ci/submit-coverage b/ci/submit-coverage
--- a/ci/submit-coverage
+++ b/ci/submit-coverage
@@ -22,6 +22,24 @@ if [[ ! -e ${REPORT} ]]; then
     exit 1
 fi
 
+if ! grep -q SimpleCov "${REPORT}"; then
+    echo "SimpleCov report (${REPORT}) does not contain any SimpleCov data: $(cat ${REPORT})"
+    exit 1
+fi
+
+if [[ ! -e "${GKE_REPORT}" ]]; then
+    echo "GKE SimpleCov report not found :("
+    ls -laR ci/authn-k8s/output
+    exit 1
+fi
+
+if ! grep -q SimpleCov "${GKE_REPORT}"; then
+    echo "SimpleCov report (${GKE_REPORT}) does not contain any SimpleCov data: $(cat ${GKE_REPORT})"
+    exit 1
+fi
+
+echo "SimpleCov Reports Found: ${REPORT}, ${GKE_REPORT}"
+
 if [[ ! -x ${BIN} ]]; then
     echo "cc-test-reporter binary not found, not reporting coverage data to code climate"
     ls -laR ${DIR}
@@ -29,12 +47,9 @@ if [[ ! -x ${BIN} ]]; then
     exit 1
 fi
 
-if [[ ! -e "${GKE_REPORT}" ]]; then
-    echo "GKE report not found :("
-    ls -laR ci/authn-k8s/output
-    exit 1
-fi
-echo "GKE report found"
+
+# Preserve a pre-merge version of the results from the non gke test branches.
+cp "${REPORT}" "${DIR}/.resultset-non-gke.json"
 
 # Merge GKE report with the already combined cucumber and rspec results.
 # -s loads input files into an array
