Responses to sgnn7 review comments

diff --git a/ci/submit-coverage b/ci/submit-coverage
--- a/ci/submit-coverage
+++ b/ci/submit-coverage
@@ -11,58 +11,56 @@
 
 set -eux
 
-dir="coverage"
-bin="cc-test-reporter"
-report="${dir}/.resultset.json"
+DIR="coverage"
+BIN="cc-test-reporter"
+REPORT="${DIR}/.resultset.json"
+GKE_REPORT="ci/authn-k8s/output/simplecov-resultset-authnk8s-gke.json"
 
-if [[ ! -e ${report} ]]; then
-    echo "SimpleCov report (${report}) not found"
-    ls -laR ${dir}
-    return 1
+if [[ ! -e ${REPORT} ]]; then
+    echo "SimpleCov report (${REPORT}) not found"
+    ls -laR ${DIR}
+    exit 1
 fi
 
-if [[ ! -x ${bin} ]]; then
+if [[ ! -x ${BIN} ]]; then
     echo "cc-test-reporter binary not found, not reporting coverage data to code climate"
-    ls -laR ${dir}
+    ls -laR ${DIR}
     # report is present but reporter binary is not, definitely a bug, exit error.
-    return 1
+    exit 1
 fi
 
-gke_report="ci/authn-k8s/output/simplecov-resultset-authnk8s-gke.json"
-if [[ -e "${gke_report}" ]]; then
-    echo "GKE Report found"
-
-    # Merge GKE report with the already combined cucumber and rspec results.
-    # -s loads input files into an array
-    # * merges objects
-    jq -s '.[0] * .[1]' "${report}" "${gke_report}" > simplecov_combined
-    # This mv is safe as it happens after all the parallel tests are complete.
-    mv simplecov_combined "${report}"
-
-    # Simplecov excludes files not within the current repo, it also needs to
-    # be able to read all the files referenced within the report. As the reports
-    # are generated in containers, the absolute paths contained in the report
-    # are not valid outside that container. This sed fixes the paths
-    # So they are correct relative to the Jenkins workspace.
-    sed -i -E "s+/(opt|src)/conjur-server+${WORKSPACE}+g" "${dir}/.resultset.json"
-
-    # Now need to regenerate the html report, as it was generated before
-    # the GKE results were merged in.
-    pushd ci/coverage-report-generator
-        ./run.sh
-    popd
-else
+if [[ ! -e "${GKE_REPORT}" ]]; then
     echo "GKE report not found :("
     ls -laR ci/authn-k8s/output
     exit 1
 fi
+echo "GKE report found"
+
+# Merge GKE report with the already combined cucumber and rspec results.
+# -s loads input files into an array
+# * merges objects
+jq -s '.[0] * .[1]' "${REPORT}" "${GKE_REPORT}" > simplecov_combined
+# This mv is safe as it happens after all the parallel tests are complete.
+mv simplecov_combined "${REPORT}"
+
+# Simplecov excludes files not within the current repo, it also needs to
+# be able to read all the files referenced within the report. As the reports
+# are generated in containers, the absolute paths contained in the report
+# are not valid outside that container. This sed fixes the paths
+# So they are correct relative to the Jenkins workspace.
+sed -i -E "s+/(opt|src)/conjur-server+${WORKSPACE}+g" "${REPORT}"
+
+# Now need to regenerate the html report, as it was generated before
+# the GKE results were merged in.
+pushd ci/coverage-report-generator
+    ./run.sh
+popd
 
 echo "Coverage reports prepared, submitting to CodeClimate."
 # vars GIT_COMMIT, GIT_BRANCH & TRID are set by ccCoverage.dockerPrep
 
-./${bin} after-build \
+./${BIN} after-build \
     --coverage-input-type "simplecov"\
-    --id "${TRID}" \
-    && echo "Successfully Reported Coverage Data"
+    --id "${TRID}"
 
-  set +x
+echo "Successfully Reported Coverage Data"
