Deploy Google function in CI
- _What's changed? Why were these changes made?_
     - Added a new stage to Jenkins file, the stage deploys A Google function that can be invoked with audience parameter, and returns an identity token
     - New python source file which contains the function code.
     - Few new script
        - deploy function
        - cleanup funciton
        - get function tokens by invoking the function and writes to files
        - get compute engine tokens, refactored the script from the Jenkins file to a script file
        - run gcloud - a script that runs Google SDK container used to deploy/delete the function
        -  secrets.yaml used by summon to provision the google service account key

Connected to #[relevant GitHub issues, #1829

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -66,6 +66,15 @@ cucumber_authenticators_azure() {
 cucumber_authenticators_gcp() {
   : DOC - Runs Cucumber GCP Authenticator features
 
+  # Ensure that token files are available,
+  # by checking if one of the expected token files exists.
+  gcp_token_file="authn-gcp/tokens/gcp_token_valid"
+
+  if ! [ -f "$gcp_token_file" ]; then
+    echo "GCP token file '$gcp_token_file' not found."
+    exit 1
+  fi
+
   _run_cucumber_tests authenticators_gcp "" "$(_get_gcp_env_args)"
 }
 
@@ -260,11 +269,7 @@ _get_azure_env_args() {
 }
 
 _get_gcp_env_args() {
-  gcp_token_file="authn-gcp/tokens/gcp_token_valid"
-  if ! [ -f "$gcp_token_file" ]; then
-    echo "GCP token file $gcp_token_file does not exist."
-    exit 1
-  fi
+
 
   decoded_gcp_token_payload=$(_get_gcp_token_payload "$gcp_token_file")
 
